name: VENDOR_BOOT - TWRP

on:
  push:
    branches:
      - 'twrp-12.1'

    paths:
      - 'version.mk'
        
jobs:
  build:
    name: Build vendor_boot by ${{ github.actor }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v4
      
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main
      
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24
        
    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libtinfo5 libgflags-dev
        sudo add-apt-repository universe
        sudo apt -y install libncurses5
    - name: Install OpenJDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Install Git-Repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo
    - name: Initialize Repo
      run: |
        rm -rf *.mk *.bp *.md *.prop *.sh prebuilt recovery
        mkdir twrp; cd twrp
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
        sed -i '/<remove-project name="platform\/external\/gflags"  \/>/d' .repo/manifests/remove-minimal.xml
        
    - name: Repo Sync
      run: |
        cd twrp; repo sync -j$(nproc --all) --force-sync
      
    - name: Clone Device Tree
      run: |
        cd twrp; git clone https://github.com/cd-Crypton/custom_recovery_tree_samsung_a55x -b twrp-12.1 ./device/samsung/a55x
        cd device/samsung/a55x
        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "VERSION=$(cat version.mk | grep '^TW_DEVICE_VERSION' | awk '{print $3}')" >> $GITHUB_ENV
        echo "COMMIT_ID2=$(git log --pretty=format:"%H" --grep="Unofficial Build Release" | sed -n '2p')" >> $GITHUB_ENV
      
    - name: Building Image 
      run: |
        cd twrp; source build/envsetup.sh; export ALLOW_MISSING_DEPENDENCIES=true
        lunch twrp_a55x-eng; mka vendorbootimage
        cd out/target/product/a55x
        tar -cvf twrp-vendor_boot.tar vendor_boot.img
      
    - name: Set Build Date # Output will be use in Release
      run: |
        echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
    
    - name: Set Body
      run: |
        echo -e \
        "
        ## Unofficial Build for Samsung Galaxy A55 5G (a55x)
        _Note: Flash at your own risk. This build were still in the process of testing._
        ### Resources
        * [TWRP Manifest](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp/tree/twrp-12.1)
        * [Device Tree](https://github.com/cd-Crypton/custom_recovery_tree_samsung_a55x/tree/twrp-12.1)
        
        Build Device: a55x
        Build Date: ${{ env.BUILD_DATE }}
        Build Release: Unofficial Beta
        Build Branch: 12.1 (v3.7.1)
        Compatibility: Android 12+
        Custom Version: ${{ env.VERSION }}
        ### Notes
        This twrp-vendor_boot.tar can be flash via ODIN software.
        ### What's new?
        * To be edited...
        * [Full Changelog](https://github.com/cd-Crypton/custom_recovery_tree_samsung_a55x/compare/${{ env.COMMIT_ID2 }}...${{ env.COMMIT_ID }})
        ### Trigger Event
        _This build were compiled by triggering branch twrp-12.1 of current tree, triggered by a push event in [version makefile](https://github.com/cd-Crypton/custom_recovery_tree_samsung_a55x/blob/twrp-12.1/version.mk)._
        * [Last Commit](https://github.com/cd-Crypton/custom_recovery_tree_samsung_a55x/commit/${{ env.COMMIT_ID }})
        " > changelog.txt
    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          twrp/out/target/product/a55x/twrp-vendor_boot.tar
          twrp/out/target/product/a55x/obj/PACKAGING/vendor_ramdisk_fragments_intermediates/recovery.cpio.lz4
        name: TWRP Release Build for Samsung Galaxy A55 5G (a55x) // ${{ env.BUILD_DATE }}
        tag_name: A55X-${{ env.VERSION }}
        body_path: changelog.txt
